# Generated by Django 4.2.5 on 2023-09-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_user_alter_category_options_alter_expense_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='owner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
